seed: 2098
num_scenarios: 20
map_config: SSC
headless_rendering: false
save_images: false
max_steps: 300
start_with_manual_control: false
patch_geneneration_iterations: 250
save_probmaps: false
lane_detection_model: resa 
simulator_window_size:
- 800
- 288
policy: LaneDetectionPolicyE2E
attack_config:
  attack_at_meter: 30
  two_pass_attack: true
  place_patch_in_image_stream: true