seed: 1235
num_scenarios: 1
map_config: SCS
headless_rendering: false
save_images: false
max_steps: 800
start_with_manual_control: false
simulator_window_size:
- 800
- 288
policy: LaneDetectionPolicyE2E
attack_config:
  attack_at_meter: 20
  two_pass_attack: true