seed: 1000
num_scenarios: 20
map_config: SSS
headless_rendering: false
save_images: true
max_steps: 2000
start_with_manual_control: false
patch_geneneration_iterations: 100
save_probmaps: true
lane_detection_model: erfnet
patch_size_meters:
- 1.0
- 1.0
simulator_window_size:
- 800
- 288
policy: LaneDetectionPolicyE2E
attack_config:
  attack_at_meter: 30
  two_pass_attack: true
  patch_color_replace: true
