seed: 1235
num_scenarios: 1
map_config: SSC
headless_rendering: false
save_images: true
max_steps: 5000
start_with_manual_control: true
simulator_window_size:
- 1280
- 720
policy: LaneDetectionPolicyE2E
attack_config: null
use_lane_camera: true