seed: 1235
num_scenarios: 100
map_config: SS
headless_rendering: false
save_images: false
max_steps: 5000
start_with_manual_control: false
simulator_window_size:
- 1280
- 720
policy: LaneDetectionPolicyE2E
attack_config: null